version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: scp_root
      POSTGRES_PASSWORD: VitoRkhaled123.
      POSTGRES_DB: scp_bd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data: